'use client';
import {useCallback,useEffect,useState} from 'react';
import {Activity,RefreshCw,ShieldCheck,CalendarClock} from 'lucide-react';
type P={id:string;created_at:string;valid_until:string;price:number;decision:'trade'|'flat';direction:'up'|'range'|'down';p_up:number;p_range:number;p_down:number;target_low:number;target_high:number;status:string;model_version:string;execution_json:string;abandon_json:string;indicators_json:string};
type SessionStat={label:string;samples:number;direction_hit_rate:number|null;direction_ci_low:number|null;direction_ci_high:number|null};
type ScorePart={code:string;label:string;points:number;observed:unknown;rule:string;evidence:string};
type Rejection={code:string;message:string};
type Candidate={name:string;label:string;score:number|null;rr_tp1:number|null;status:'qualified'|'rejected'|'not_triggered';score_breakdown:ScorePart[];hard_rejections:Rejection[]};
type Strategy={name:string;label:string;score:number;rr_tp1:number;selection_reason?:string;reasons?:string[];wait_for?:string[];candidates?:Candidate[];entry?:number[];stop?:number[];tp1?:number[];tp2?:number[]};
type StrategyStat={label:string;samples:number;direction_hit_rate:number|null;direction_ci_low:number|null;direction_ci_high:number|null;target_range_hit_rate:number|null;brier:number|null;sample_stage:string;warnings:string[];metric_scope:string};
type Stats={samples:number;direction_hit_rate:number|null;direction_ci_low:number|null;direction_ci_high:number|null;target_range_hit_rate:number|null;target_touched_rate:number|null;brier:number|null;calibration_ready:boolean;calibration_stage:string;probability_quality:number|null;by_session?:Record<string,SessionStat>;by_strategy?:Record<string,StrategyStat>};
type Health={checked_at:string;heartbeat:string|null;market_time:string|null;market_status:string;weekend:boolean;last_publish_at:string|null;missed_count:number;last_run:{message:string;finished_at:string|null}|null;issues:{key:string;message:string}[];settlements:{pending:number;items:{ledger:string;prediction_id:string;message:string;attempts:number|null}[]};scope:string};
type Data={health?:Health;shadow?:{report_text:string}|null;shadow_error?:string|null;current:P|null;rolling20:Stats;rolling60:Stats;history?:P[];generated_at:string};
const labels={up:'上涨',range:'震荡',down:'下跌'};
const fp=(n:number|null|undefined)=>n==null?'—':`${(n*100).toFixed(1)}%`;
const parse=(s:string|undefined)=>{try{return JSON.parse(s||'[]')}catch{return[]}};
const context=(s:string|undefined)=>{try{return JSON.parse(s||'{}')}catch{return{}}};
const market=(s:string|undefined)=>context(s)._market||{};
const strategyFor=(p:P|null)=>p?(context(p.indicators_json)._strategy as Strategy|undefined):undefined;
const band=(values:number[]|undefined)=>values?.length===2?`${values[0].toFixed(2)}–${values[1].toFixed(2)}`:null;
const planFor=(p:P|null)=>{if(!p)return null;const strategy=strategyFor(p);if(strategy){if(strategy.name==='flat')return{advice:`空仓等待：${strategy.reasons?.join('；')||'没有候选通过全部门槛'}`,tp1:null,tp2:null};return{advice:`${strategy.label}：${strategy.selection_reason||'当前评分最高且通过硬门槛'}。理想入场 ${band(strategy.entry)}，失效区 ${band(strategy.stop)}。`,tp1:band(strategy.tp1),tp2:band(strategy.tp2)}}const ctx=context(p.indicators_json),price=p.price,atr=Math.max(.8,Number(ctx.M15?.atr||0));const levels=['M15','M30','H1'].flatMap(tf=>['ma20','ma60','ma200'].map(key=>Number(ctx[tf]?.[key])).filter(Number.isFinite));const support=Math.max(...levels.filter(x=>x<price),price-atr),resistance=Math.min(...levels.filter(x=>x>price),price+atr);return{advice:`旧版报告：支撑 ${support.toFixed(2)}，阻力 ${resistance.toFixed(2)}。`,tp1:null,tp2:null}};
export default function Home(){const[data,setData]=useState<Data|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[isLocal,setIsLocal]=useState(false);const[liveHealth,setLiveHealth]=useState<Health|null>(null);const[healthOffline,setHealthOffline]=useState(false);const[clockNow,setClockNow]=useState(0);const[elapsed,setElapsed]=useState(0);const[status,setStatus]=useState<'ready'|'working'|'success'|'error'>('ready');const[statusNote,setStatusNote]=useState('等待操作');const[lastFinished,setLastFinished]=useState('');const base=process.env.NEXT_PUBLIC_BASE_PATH??'';const load=useCallback(()=>fetch(base+'/data/dashboard.json?'+Date.now(),{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('尚无真实数据');const result=await r.json() as Data;setData(result);return result}),[base]);
useEffect(()=>{queueMicrotask(()=>setIsLocal(['localhost','127.0.0.1'].includes(window.location.hostname)));load().then(()=>setStatusNote('数据已载入，可以查看')).catch(e=>{setError(e.message);setStatus('error');setStatusNote('初始数据载入失败')})},[load]);
useEffect(()=>{if(!busy)return;const timer=window.setInterval(()=>setElapsed(value=>value+1),1000);return()=>window.clearInterval(timer)},[busy]);
useEffect(()=>{const updateClock=()=>setClockNow(Date.now());updateClock();const clock=window.setInterval(updateClock,30000);return()=>window.clearInterval(clock)},[]);
useEffect(()=>{if(!isLocal)return;let active=true;const check=async()=>{try{const r=await fetch('http://127.0.0.1:8765/health',{cache:'no-store',signal:AbortSignal.timeout(5000)});if(!r.ok)throw Error('health');const h=await r.json() as Health;if(active){setLiveHealth(h);setHealthOffline(false)}}catch{if(active)setHealthOffline(true)}};void check();const timer=window.setInterval(check,30000);return()=>{active=false;window.clearInterval(timer)}},[isLocal]);
async function run(){let runNotice='';const previousId=data?.current?.id;setElapsed(0);setBusy(true);setStatus('working');setStatusNote(isLocal?'正在连接本机分析服务':'正在获取 GitHub 最新数据');setError('');try{if(isLocal){const r=await fetch('http://127.0.0.1:8765/run',{method:'POST'});if(!r.ok){const result=await r.json().catch(()=>null) as {error?:string}|null;throw Error(result?.error?.trim()||'分析没有成功，请确认 MT5 已打开并登录')}const reply=await r.json() as {output?:string};const outcome=context(reply.output);if(outcome.code&&outcome.code!=='ok')runNotice=outcome.message||'本次未完成分析'}const latest=await load();if(runNotice)throw Error(runNotice);setStatus('success');setLastFinished(new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit'}));setStatusNote(isLocal?'分析完成，页面数据已更新':latest.current?.id===previousId?'刷新完成，目前没有更新的报告':'刷新完成，已载入最新报告')}catch(e){const message=e instanceof Error?e.message:'';const friendly=message.includes('fetch')?'无法连接本机分析服务，请重新打开本地网页；如果仍然失败，请重启电脑后再试':message||'运行失败';setError(friendly);setStatus('error');setStatusNote('操作失败，请查看下面的原因')}finally{setBusy(false)}}
const health=liveHealth??data?.health;const snapshotOld=Boolean(health&&clockNow-new Date(health.checked_at).getTime()>130*60000);const c=data?.current,s=data?.rolling20,day=market(data?.current?.indicators_json),plan=planFor(data?.current??null),strategy=strategyFor(data?.current??null);const reportUnavailable=healthOffline||snapshotOld||health?.market_status==='stale_quote'||health?.market_status==='mt5_error'||Boolean(c&&clockNow>new Date(c.valid_until).getTime());const probs=c?[['上涨',c.p_up,'up'],['震荡',c.p_range,'range'],['下跌',c.p_down,'down']]:[];const workingText=isLocal?(elapsed<3?'正在连接本机服务':elapsed<10?'正在读取 MT5 多周期数据':elapsed<25?'正在计算指标并生成报告':'正在发送通知并上传网页数据'):'正在检查 GitHub 上的最新报告';const shownStatus=busy?workingText:statusNote;
return <main className="min-h-screen bg-[#090b0d] text-[#f5f1e8]"><header className="sticky top-0 z-10 border-b border-white/8 bg-[#0c0e10]/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-4 sm:px-6"><div><div className="flex items-center gap-2 font-semibold tracking-[.12em] text-[#ddb657] sm:tracking-[.16em]"><Activity size={19}/>AURUM SIGNAL</div><p className="mt-1 text-[11px] text-zinc-500 sm:text-xs">XAUUSD 预测与验证台</p></div><button onClick={run} disabled={busy} className="flex min-h-11 shrink-0 items-center gap-2 rounded-xl bg-[#d7a73c] px-3 text-sm font-bold text-black shadow-lg shadow-amber-950/30 sm:px-4"><RefreshCw size={17} className={busy?'animate-spin':''}/>{busy?(isLocal?'正在分析…':'正在刷新…'):(isLocal?'立即分析':'刷新数据')}</button></div></header>
<div className="mx-auto max-w-7xl space-y-5 px-4 py-5 sm:px-6"><section aria-live="polite" className={'overflow-hidden rounded-2xl border px-4 py-3 '+(status==='error'?'border-rose-500/30 bg-rose-500/10':status==='success'?'border-emerald-500/30 bg-emerald-500/10':'border-[#d7a73c]/25 bg-[#d7a73c]/[.07]')}><div className="flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className={'h-2.5 w-2.5 shrink-0 rounded-full '+(busy?'animate-pulse bg-[#f3c75f]':status==='error'?'bg-rose-400':status==='success'?'bg-emerald-400':'bg-zinc-500')}/><div className="min-w-0"><p className="text-sm font-semibold">{shownStatus}</p><p className="mt-1 text-xs text-zinc-400">{isLocal?'本地模式：可读取 MT5 并立即生成报告':'公共查看模式：刷新 GitHub 上最近一次已上传的报告'}</p></div></div><div className="shrink-0 text-right text-xs text-zinc-400">{busy?`已等待 ${elapsed} 秒`:lastFinished?`完成于 ${lastFinished}`:'就绪'}</div></div>{busy&&<div className="mt-3 h-1 overflow-hidden rounded-full bg-white/10"><div className="h-full w-1/2 animate-pulse rounded-full bg-[#d7a73c]"/></div>}</section>{error&&<div className="rounded-xl border border-amber-500/30 bg-amber-500/10 px-4 py-3 text-sm text-amber-200">{error}。定时数据仍可正常展示；电脑手动分析需启动本地桥接。</div>}
<section className="rounded-2xl border border-amber-500/25 bg-[#111417] p-5" aria-live="polite"><h2 className="font-semibold text-[#f3c75f]">运行检查与漏报提示</h2><p className="mt-2 text-xs text-zinc-400">{isLocal?(healthOffline?'无法连接本机后台，以下可能为旧快照':'本机实时核查，每30秒刷新'):'公共页面为最近上传快照，不能据此确认后台实时在线'}</p>{snapshotOld&&<p className="mt-3 text-sm text-amber-200">运行快照已超过两小时十分钟未更新，请检查电脑、后台或上传连接。</p>}{health?<><div className="mt-4 grid gap-2 text-sm sm:grid-cols-2"><p>最近核查：{new Date(health.checked_at).toLocaleString('zh-CN')}</p><p>行情：{health.market_status==='ok'?'最近读取正常':health.market_status==='stale_quote'?(health.weekend?'周末报价过期，暂停新预测':'报价过期，请检查休市或连接'):health.market_status==='mt5_error'?'MT5读取失败':'尚未核查'}</p><p>漏生成：{health.missed_count}个时点</p><p>到期待核查：{health.settlements.pending}条</p><p>最近运行：{health.last_run?.message??'等待首轮'}</p><p>最近上传成功：{health.last_publish_at?new Date(health.last_publish_at).toLocaleString('zh-CN'):'尚无成功记录'}</p></div><div className="mt-3 text-sm leading-7 text-amber-200">{health.issues.length?health.issues.map(x=><p key={x.key}>{x.message}</p>):<p className="text-zinc-400">本次检查未发现漏报或待处理异常。</p>}</div>{health.settlements.items.length>0&&<details className="mt-3 text-sm"><summary className="cursor-pointer">查看待结算原因（最多30条）</summary>{health.settlements.items.map(x=><p key={x.ledger+x.prediction_id} className="mt-2 break-all text-zinc-400">{x.ledger==='shadow'?'影子':'原账本'} · {x.prediction_id}：{x.message}；已核查{x.attempts??0}次</p>)}</details>}<p className="mt-3 text-xs text-zinc-500">{health.scope}</p></>:<p className="mt-3 text-sm text-zinc-400">等待首次运行检查。</p>}</section>
<section className="grid gap-5 lg:grid-cols-[1.5fr_.8fr]"><article className="rounded-3xl border border-[#d7a73c]/25 bg-gradient-to-br from-[#191814] to-[#101214] p-5 shadow-2xl shadow-black/20 sm:p-7"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-medium text-zinc-500">{reportUnavailable?'最近报告价格（非实时）':'当前抓取价格'}</p><div className="mt-1 text-4xl font-semibold tracking-tight text-[#f3c75f] sm:text-5xl">{c?c.price.toFixed(2):'—'}</div><p className="mt-3 text-xs text-zinc-500">{c?`生成于 ${new Date(c.created_at).toLocaleString('zh-CN')}`:'等待首次数据'}</p><h1 className="mt-5 text-2xl font-semibold sm:text-3xl">{reportUnavailable?'等待有效行情':strategy?.label??(c?(c.decision==='trade'?`值得等待${labels[c.direction]}条件`:'当前空仓'):'尚未生成预测')}</h1><p className="mt-3 text-sm leading-7 text-zinc-400">{c?`有效至 ${new Date(c.valid_until).toLocaleString('zh-CN')}，模型 ${c.model_version}`:'请保持 MT5 在线后运行本地工作流。'}</p></div><span className={'h-fit rounded-full px-3 py-1.5 text-sm '+(c?.decision==='trade'?'bg-emerald-400/10 text-emerald-300':'bg-amber-400/10 text-amber-300')}>{reportUnavailable?'仅供回看':c?.decision==='trade'?'有条件交易':'不交易'}</span></div>
<div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4"><div className="metric"><span>昨日收盘</span><strong>{day.previous_close??'—'}</strong></div><div className="metric"><span>今日开盘</span><strong>{day.today_open??'—'}</strong></div><div className="metric"><span>今日最高 / 最低</span><strong className="text-base">{day.today_high??'—'} / {day.today_low??'—'}</strong></div><div className="metric"><span>今日涨跌 / 振幅</span><strong className={(day.change??0)>=0?'text-emerald-300':'text-rose-300'}>{day.change==null?'—':`${day.change>=0?'+':''}${Number(day.change).toFixed(2)} · ${(Number(day.amplitude_pct)*100).toFixed(2)}%`}</strong></div></div>
<div className="mt-7 grid gap-3 sm:grid-cols-3">{probs.map(x=><div key={x[0] as string} className={'metric '+(c?.direction===x[2]?'selected':'')}><span>{x[0]}</span><strong>{fp(x[1] as number)}</strong></div>)}</div>
<div className="mt-5 grid gap-3 md:grid-cols-2"><div className="rule"><b className="text-emerald-300">执行条件</b>{parse(c?.execution_json).map((x:string)=><p key={x}>• {x}</p>)}</div><div className="rule"><b className="text-rose-300">放弃条件</b>{parse(c?.abandon_json).map((x:string)=><p key={x}>• {x}</p>)}</div></div><div className="mt-3 rounded-xl border border-[#d7a73c]/20 bg-[#d7a73c]/[.07] p-4 text-sm"><b className="text-[#f3c75f]">当前建议</b><p className="mt-2 leading-6 text-zinc-200">{reportUnavailable?'当前行情或报告已失效，历史方案仅供回看，等待下一次有效更新。':plan?.advice??'—'}</p>{!reportUnavailable&&plan?.tp1&&<p className="mt-3 text-zinc-300">TP1：<b className="text-[#e3b64f]">{plan.tp1}</b>　TP2：<b className="text-[#e3b64f]">{plan.tp2}</b></p>}</div><div className="mt-3 rounded-xl bg-black/25 p-4 text-sm">目标价格区间：<b className="text-[#e3b64f]">{c?`${c.target_low}–${c.target_high}`:'—'}</b></div></article>
<aside className="rounded-3xl border border-white/8 bg-[#111417] p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">系统状态</h2><ShieldCheck className="text-emerald-400" size={20}/></div>{['MT5 M5/M15/M30/H1','MACD · Stoch · ADX · MA','新闻与经济日历','只读模式，禁止自动下单'].map(x=><div key={x} className="mt-3 rounded-xl bg-white/[.035] px-3 py-3 text-sm text-zinc-300">{x}</div>)}<div className="mt-4 rounded-xl bg-black/25 p-4 text-sm"><div className="flex items-center gap-2"><CalendarClock size={16} className="text-[#ddb657]"/>更新与提醒</div><p className="mt-2 leading-6 text-zinc-500">北京时间工作日固定生成三次完整报告：<br/>08:30 · 15:00 · 20:00；每份统一观察4小时。</p></div><div className="mt-3 rounded-xl border border-amber-500/20 bg-amber-500/[.06] p-4 text-sm"><b className="text-amber-200">每日交易限制</b><p className="mt-2 leading-6 text-zinc-400">系统只读核验MT5当日XAUUSD开仓成交；达到2次或无法核验时，自动停止给出新交易建议。</p></div></aside></section>
{strategy?.candidates&&<section className="rounded-2xl border border-white/8 bg-[#111417] p-5"><h2 className="font-semibold">候选横向比较</h2><p className="mt-2 text-xs text-zinc-500">硬性淘汰先于评分；所有候选从50分起算。未触发、被淘汰与合格候选均保留审计记录。</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">{strategy.candidates.map(x=><details key={x.name} className={'rounded-xl border p-4 '+(x.status==='qualified'?'border-emerald-500/30 bg-emerald-500/[.06]':x.status==='rejected'?'border-rose-500/20 bg-rose-500/[.04]':'border-white/8 bg-black/20')}><summary className="cursor-pointer list-none"><div className="flex items-center justify-between gap-2"><b>{x.label}</b><span className="text-sm text-[#e3b64f]">{x.score==null?'未触发':`${x.score.toFixed(1)}分`}</span></div><p className="mt-2 text-xs text-zinc-500">{x.status==='qualified'?`已通过 · TP1 ${x.rr_tp1?.toFixed(2)}R`:x.status==='rejected'?'已淘汰':'本轮无确认'}</p></summary><div className="mt-3 space-y-2 border-t border-white/8 pt-3 text-xs text-zinc-400">{x.score_breakdown.map(part=><p key={part.code}><span className={part.points>=0?'text-emerald-300':'text-rose-300'}>{part.points>=0?'+':''}{part.points}</span> {part.label}：{part.rule}</p>)}{x.hard_rejections.map(reason=><p key={reason.code} className="text-rose-300">{reason.code}：{reason.message}</p>)}</div></details>)}</div>{strategy.selection_reason&&<p className="mt-4 rounded-xl bg-[#d7a73c]/[.07] p-3 text-sm text-[#f3c75f]">主建议胜出原因：{strategy.selection_reason}</p>}</section>}
<section className="rounded-2xl border border-[#d7a73c]/25 bg-[#111417] p-5"><h2 className="font-semibold text-[#f3c75f]">日内定调与固定会话影子测试</h2><p className="mt-2 text-xs text-zinc-400">北京时间08:30亚洲定调 · 15:00欧洲报告 · 20:00美国报告 · 至少30个交易日</p><p className="mt-4 whitespace-pre-line text-sm leading-7 text-zinc-200">{data?.shadow?.report_text??(data?.shadow_error?`影子版本本轮失败：${data.shadow_error}`:'等待首次影子运行；未生成的数据不计入样本。')}</p></section>
<section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['三时段正式样本',s?.samples??0,'仅session-3x-v1；手动及旧两小时版本不计入'],['方向命中率',fp(s?.direction_hit_rate),s?.direction_ci_low==null?'样本积累中':`95%区间 ${fp(s.direction_ci_low)}–${fp(s.direction_ci_high)}`],['Brier分数',s?.brier?.toFixed(3)??'—','概率质量，越低越好'],['历史概率质量',s?.probability_quality==null?'样本积累中':`${s.probability_quality}/100`,s?.calibration_stage??'需100个正式样本']].map(x=><div key={x[0] as string} className="rounded-2xl border border-white/8 bg-[#111417] p-5"><span className="text-sm text-zinc-500">{x[0]}</span><div className="mt-2 text-2xl font-semibold">{x[1]}</div><p className="mt-1 text-xs text-zinc-500">{x[2]}</p></div>)}</section>
<section className="rounded-2xl border border-white/8 bg-[#111417] p-5"><h2 className="font-semibold">分时段预测方向命中</h2><p className="mt-2 text-xs text-zinc-500">每份固定观察4小时；这是预测结算统计，不是交易胜率或收益。</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{Object.values(s?.by_session??{}).map(x=><div key={x.label} className="metric"><span>{x.label}时段 · {x.samples}个样本</span><strong>{fp(x.direction_hit_rate)}</strong><p className="mt-1 text-xs text-zinc-500">{x.direction_ci_low==null?'置信区间待积累':`95%区间 ${fp(x.direction_ci_low)}–${fp(x.direction_ci_high)}`}</p></div>)}</div></section>
<section className="rounded-2xl border border-white/8 bg-[#111417] p-5"><h2 className="font-semibold">分主建议类型的预测记录</h2><p className="mt-2 text-xs text-zinc-500">少于30个样本为不足，30–99仅作探索，100以上才进入稳定观察；未模拟真实成交盈亏。</p><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(s?.by_strategy??{}).map(([name,x])=><div key={name} className="metric"><span>{x.label} · {x.samples}个样本</span><strong>{fp(x.direction_hit_rate)}</strong><p className="mt-1 text-xs text-zinc-500">目标区间 {fp(x.target_range_hit_rate)} · Brier {x.brier?.toFixed(3)??'—'}</p>{x.warnings.map(w=><p key={w} className="mt-1 text-xs text-amber-300">{w}</p>)}</div>)}</div></section>
<footer className="py-3 text-center text-xs text-zinc-600">研究与决策辅助 · 不承诺盈利 · 不执行交易</footer></div></main>}


