'use client';
import {useCallback,useEffect,useState} from 'react';
import {Activity,RefreshCw,ShieldCheck,CalendarClock} from 'lucide-react';
type P={id:string;created_at:string;valid_until:string;price:number;decision:'trade'|'flat';direction:'up'|'range'|'down';p_up:number;p_range:number;p_down:number;target_low:number;target_high:number;status:string;model_version:string;execution_json:string;abandon_json:string;indicators_json:string};
type Stats={samples:number;direction_hit_rate:number|null;direction_ci_low:number|null;direction_ci_high:number|null;target_range_hit_rate:number|null;target_touched_rate:number|null;brier:number|null;calibration_ready:boolean;calibration_stage:string;probability_quality:number|null};
type Data={current:P|null;rolling20:Stats;rolling60:Stats;history?:P[];generated_at:string};
const labels={up:'上涨',range:'震荡',down:'下跌'};
const fp=(n:number|null|undefined)=>n==null?'—':`${(n*100).toFixed(1)}%`;
const parse=(s:string|undefined)=>{try{return JSON.parse(s||'[]')}catch{return[]}};
const context=(s:string|undefined)=>{try{return JSON.parse(s||'{}')}catch{return{}}};
const market=(s:string|undefined)=>context(s)._market||{};
const planFor=(p:P|null)=>{if(!p)return null;const ctx=context(p.indicators_json),price=p.price,atr=Math.max(.8,Number(ctx.M15?.atr||0));const levels=['M15','M30','H1'].flatMap(tf=>['ma20','ma60','ma200'].map(key=>Number(ctx[tf]?.[key])).filter(Number.isFinite)).concat(['previous_close','today_open','today_high','today_low'].map(key=>Number(ctx._market?.[key])).filter(Number.isFinite));const support=Math.max(...levels.filter(x=>x<price),price-atr),resistance=Math.min(...levels.filter(x=>x>price),price+atr),width=Math.max(.8,atr*.25),zone=(x:number)=>[x-width,x+width] as const,fmt=([a,b]:readonly[number,number])=>`${a.toFixed(2)}–${b.toFixed(2)}`;const s=zone(support),r=zone(resistance),entry=(s[0]+s[1])/2,shortEntry=(r[0]+r[1])/2,target=(x:number)=>zone(x);const longTp1=target(Math.max((r[0]+r[1])/2,entry+atr)),longTp2=target(Math.max((r[0]+r[1])/2+atr,entry+atr*2)),shortTp1=target(Math.min((s[0]+s[1])/2,shortEntry-atr)),shortTp2=target(Math.min((s[0]+s[1])/2-atr,shortEntry-atr*2));if(p.direction==='up')return {advice:`偏多观察：等 ${fmt(s)} 回踩企稳做多；若不回踩，只观察 ${fmt(r)} 的有效突破。`,tp1:fmt(longTp1),tp2:fmt(longTp2)};if(p.direction==='down')return {advice:`偏空观察：等 ${fmt(r)} 反弹受阻做空；若不反弹，只观察 ${fmt(s)} 的有效跌破。`,tp1:fmt(shortTp1),tp2:fmt(shortTp2)};return {advice:`当前不操作：上方关注 ${fmt(r)} 的突破确认，下方关注 ${fmt(s)} 的跌破确认。`,tp1:null,tp2:null}};
export default function Home(){const[data,setData]=useState<Data|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[isLocal,setIsLocal]=useState(false);const[elapsed,setElapsed]=useState(0);const[status,setStatus]=useState<'ready'|'working'|'success'|'error'>('ready');const[statusNote,setStatusNote]=useState('等待操作');const[lastFinished,setLastFinished]=useState('');const base=process.env.NEXT_PUBLIC_BASE_PATH??'';const load=useCallback(()=>fetch(base+'/data/dashboard.json?'+Date.now(),{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('尚无真实数据');const result=await r.json() as Data;setData(result);return result}),[base]);
useEffect(()=>{queueMicrotask(()=>setIsLocal(['localhost','127.0.0.1'].includes(window.location.hostname)));load().then(()=>setStatusNote('数据已载入，可以查看')).catch(e=>{setError(e.message);setStatus('error');setStatusNote('初始数据载入失败')})},[load]);
useEffect(()=>{if(!busy)return;const timer=window.setInterval(()=>setElapsed(value=>value+1),1000);return()=>window.clearInterval(timer)},[busy]);
async function run(){const previousId=data?.current?.id;setElapsed(0);setBusy(true);setStatus('working');setStatusNote(isLocal?'正在连接本机分析服务':'正在获取 GitHub 最新数据');setError('');try{if(isLocal){const r=await fetch('http://127.0.0.1:8765/run',{method:'POST'});if(!r.ok){const result=await r.json().catch(()=>null) as {error?:string}|null;throw Error(result?.error?.trim()||'分析没有成功，请确认 MT5 已打开并登录')}}const latest=await load();setStatus('success');setLastFinished(new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',second:'2-digit'}));setStatusNote(isLocal?'分析完成，页面数据已更新':latest.current?.id===previousId?'刷新完成，目前没有更新的报告':'刷新完成，已载入最新报告')}catch(e){const message=e instanceof Error?e.message:'';const friendly=message.includes('fetch')?'无法连接本机分析服务，请重新打开本地网页；如果仍然失败，请重启电脑后再试':message||'运行失败';setError(friendly);setStatus('error');setStatusNote('操作失败，请查看下面的原因')}finally{setBusy(false)}}
const c=data?.current,s=data?.rolling20,day=market(data?.current?.indicators_json),plan=planFor(data?.current??null);const probs=c?[['上涨',c.p_up,'up'],['震荡',c.p_range,'range'],['下跌',c.p_down,'down']]:[];const workingText=isLocal?(elapsed<3?'正在连接本机服务':elapsed<10?'正在读取 MT5 多周期数据':elapsed<25?'正在计算指标并生成报告':'正在发送通知并上传网页数据'):'正在检查 GitHub 上的最新报告';const shownStatus=busy?workingText:statusNote;
return <main className="min-h-screen bg-[#090b0d] text-[#f5f1e8]"><header className="sticky top-0 z-10 border-b border-white/8 bg-[#0c0e10]/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-4 sm:px-6"><div><div className="flex items-center gap-2 font-semibold tracking-[.12em] text-[#ddb657] sm:tracking-[.16em]"><Activity size={19}/>AURUM SIGNAL</div><p className="mt-1 text-[11px] text-zinc-500 sm:text-xs">XAUUSD 预测与验证台</p></div><button onClick={run} disabled={busy} className="flex min-h-11 shrink-0 items-center gap-2 rounded-xl bg-[#d7a73c] px-3 text-sm font-bold text-black shadow-lg shadow-amber-950/30 sm:px-4"><RefreshCw size={17} className={busy?'animate-spin':''}/>{busy?(isLocal?'正在分析…':'正在刷新…'):(isLocal?'立即分析':'刷新数据')}</button></div></header>
<div className="mx-auto max-w-7xl space-y-5 px-4 py-5 sm:px-6"><section aria-live="polite" className={'overflow-hidden rounded-2xl border px-4 py-3 '+(status==='error'?'border-rose-500/30 bg-rose-500/10':status==='success'?'border-emerald-500/30 bg-emerald-500/10':'border-[#d7a73c]/25 bg-[#d7a73c]/[.07]')}><div className="flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className={'h-2.5 w-2.5 shrink-0 rounded-full '+(busy?'animate-pulse bg-[#f3c75f]':status==='error'?'bg-rose-400':status==='success'?'bg-emerald-400':'bg-zinc-500')}/><div className="min-w-0"><p className="text-sm font-semibold">{shownStatus}</p><p className="mt-1 text-xs text-zinc-400">{isLocal?'本地模式：可读取 MT5 并立即生成报告':'公共查看模式：刷新 GitHub 上最近一次已上传的报告'}</p></div></div><div className="shrink-0 text-right text-xs text-zinc-400">{busy?`已等待 ${elapsed} 秒`:lastFinished?`完成于 ${lastFinished}`:'就绪'}</div></div>{busy&&<div className="mt-3 h-1 overflow-hidden rounded-full bg-white/10"><div className="h-full w-1/2 animate-pulse rounded-full bg-[#d7a73c]"/></div>}</section>{error&&<div className="rounded-xl border border-amber-500/30 bg-amber-500/10 px-4 py-3 text-sm text-amber-200">{error}。定时数据仍可正常展示；电脑手动分析需启动本地桥接。</div>}
<section className="grid gap-5 lg:grid-cols-[1.5fr_.8fr]"><article className="rounded-3xl border border-[#d7a73c]/25 bg-gradient-to-br from-[#191814] to-[#101214] p-5 shadow-2xl shadow-black/20 sm:p-7"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-medium text-zinc-500">当前抓取价格</p><div className="mt-1 text-4xl font-semibold tracking-tight text-[#f3c75f] sm:text-5xl">{c?c.price.toFixed(2):'—'}</div><p className="mt-3 text-xs text-zinc-500">{c?`生成于 ${new Date(c.created_at).toLocaleString('zh-CN')}`:'等待首次数据'}</p><h1 className="mt-5 text-2xl font-semibold sm:text-3xl">{c?(c.decision==='trade'?`值得等待${labels[c.direction]}条件`:'当前空仓'):'尚未生成预测'}</h1><p className="mt-3 text-sm leading-7 text-zinc-400">{c?`有效至 ${new Date(c.valid_until).toLocaleString('zh-CN')}，模型 ${c.model_version}`:'请保持 MT5 在线后运行本地工作流。'}</p></div><span className={'h-fit rounded-full px-3 py-1.5 text-sm '+(c?.decision==='trade'?'bg-emerald-400/10 text-emerald-300':'bg-amber-400/10 text-amber-300')}>{c?.decision==='trade'?'有条件交易':'不交易'}</span></div>
<div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4"><div className="metric"><span>昨日收盘</span><strong>{day.previous_close??'—'}</strong></div><div className="metric"><span>今日开盘</span><strong>{day.today_open??'—'}</strong></div><div className="metric"><span>今日最高 / 最低</span><strong className="text-base">{day.today_high??'—'} / {day.today_low??'—'}</strong></div><div className="metric"><span>今日涨跌 / 振幅</span><strong className={(day.change??0)>=0?'text-emerald-300':'text-rose-300'}>{day.change==null?'—':`${day.change>=0?'+':''}${Number(day.change).toFixed(2)} · ${(Number(day.amplitude_pct)*100).toFixed(2)}%`}</strong></div></div>
<div className="mt-7 grid gap-3 sm:grid-cols-3">{probs.map(x=><div key={x[0] as string} className={'metric '+(c?.direction===x[2]?'selected':'')}><span>{x[0]}</span><strong>{fp(x[1] as number)}</strong></div>)}</div>
<div className="mt-5 grid gap-3 md:grid-cols-2"><div className="rule"><b className="text-emerald-300">执行条件</b>{parse(c?.execution_json).map((x:string)=><p key={x}>• {x}</p>)}</div><div className="rule"><b className="text-rose-300">放弃条件</b>{parse(c?.abandon_json).map((x:string)=><p key={x}>• {x}</p>)}</div></div><div className="mt-3 rounded-xl border border-[#d7a73c]/20 bg-[#d7a73c]/[.07] p-4 text-sm"><b className="text-[#f3c75f]">当前建议</b><p className="mt-2 leading-6 text-zinc-200">{plan?.advice??'—'}</p>{plan?.tp1&&<p className="mt-3 text-zinc-300">TP1：<b className="text-[#e3b64f]">{plan.tp1}</b>　TP2：<b className="text-[#e3b64f]">{plan.tp2}</b></p>}</div><div className="mt-3 rounded-xl bg-black/25 p-4 text-sm">目标价格区间：<b className="text-[#e3b64f]">{c?`${c.target_low}–${c.target_high}`:'—'}</b></div></article>
<aside className="rounded-3xl border border-white/8 bg-[#111417] p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">系统状态</h2><ShieldCheck className="text-emerald-400" size={20}/></div>{['MT5 M5/M15/M30/H1','MACD · Stoch · ADX · MA','新闻与经济日历','只读模式，禁止自动下单'].map(x=><div key={x} className="mt-3 rounded-xl bg-white/[.035] px-3 py-3 text-sm text-zinc-300">✓ {x}</div>)}<div className="mt-4 rounded-xl bg-black/25 p-4 text-sm"><div className="flex items-center gap-2"><CalendarClock size={16} className="text-[#ddb657]"/>更新与提醒</div><p className="mt-2 leading-6 text-zinc-500">后台每两小时更新并结算上一预测。<br/>10:00 · 16:00 · 21:00 发送完整报告；其余时段仅在观点明显变化时提醒。</p></div></aside></section>
<section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['正式两小时样本',s?.samples??0,'21:00补充报告不计入统计'],['方向命中率',fp(s?.direction_hit_rate),s?.direction_ci_low==null?'样本积累中':`95%区间 ${fp(s.direction_ci_low)}–${fp(s.direction_ci_high)}`],['Brier分数',s?.brier?.toFixed(3)??'—','概率质量，越低越好'],['历史概率质量',s?.probability_quality==null?'样本积累中':`${s.probability_quality}/100`,s?.calibration_stage??'需100个正式样本']].map(x=><div key={x[0] as string} className="rounded-2xl border border-white/8 bg-[#111417] p-5"><span className="text-sm text-zinc-500">{x[0]}</span><div className="mt-2 text-2xl font-semibold">{x[1]}</div><p className="mt-1 text-xs text-zinc-500">{x[2]}</p></div>)}</section>
<footer className="py-3 text-center text-xs text-zinc-600">研究与决策辅助 · 不承诺盈利 · 不执行交易</footer></div></main>}


