'use client';
import {useCallback,useEffect,useState} from 'react';
import {Activity,RefreshCw,ShieldCheck,CalendarClock} from 'lucide-react';
type P={id:string;created_at:string;valid_until:string;price:number;decision:'trade'|'flat';direction:'up'|'range'|'down';p_up:number;p_range:number;p_down:number;target_low:number;target_high:number;status:string;model_version:string;execution_json:string;abandon_json:string;indicators_json:string};
type Stats={samples:number;direction_hit_rate:number|null;target_range_hit_rate:number|null;target_touched_rate:number|null;brier:number|null;calibration_ready:boolean};
type Data={current:P|null;rolling20:Stats;rolling60:Stats;history?:P[];generated_at:string};
const labels={up:'上涨',range:'震荡',down:'下跌'};
const fp=(n:number|null|undefined)=>n==null?'—':`${(n*100).toFixed(1)}%`;
const parse=(s:string|undefined)=>{try{return JSON.parse(s||'[]')}catch{return[]}};
export default function Home(){const[data,setData]=useState<Data|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[isLocal,setIsLocal]=useState(false);const base=process.env.NEXT_PUBLIC_BASE_PATH??'';const load=useCallback(()=>fetch(base+'/data/dashboard.json?'+Date.now(),{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('尚无真实数据');return await r.json() as Data}).then(setData),[base]);
useEffect(()=>{setIsLocal(['localhost','127.0.0.1'].includes(window.location.hostname));load().catch(e=>setError(e.message))},[load]);
async function run(){setBusy(true);setError('');try{if(isLocal){const r=await fetch('http://127.0.0.1:8765/run',{method:'POST'});if(!r.ok){const result=await r.json().catch(()=>null) as {error?:string}|null;throw Error(result?.error?.trim()||'分析没有成功，请确认 MT5 已打开并登录')}}await load()}catch(e){const message=e instanceof Error?e.message:'';setError(message.includes('fetch')?'无法连接本机分析服务，请重新打开本地网页；如果仍然失败，请重启电脑后再试':message||'运行失败')}finally{setBusy(false)}}
const c=data?.current,s=data?.rolling20;const probs=c?[['上涨',c.p_up,'up'],['震荡',c.p_range,'range'],['下跌',c.p_down,'down']]:[];
return <main className="min-h-screen bg-[#090b0d] text-[#f5f1e8]"><header className="sticky top-0 z-10 border-b border-white/8 bg-[#0c0e10]/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-4 sm:px-6"><div><div className="flex items-center gap-2 font-semibold tracking-[.12em] text-[#ddb657] sm:tracking-[.16em]"><Activity size={19}/>AURUM SIGNAL</div><p className="mt-1 text-[11px] text-zinc-500 sm:text-xs">XAUUSD 预测与验证台</p></div><button onClick={run} disabled={busy} className="flex min-h-11 shrink-0 items-center gap-2 rounded-xl bg-[#d7a73c] px-3 text-sm font-bold text-black shadow-lg shadow-amber-950/30 sm:px-4"><RefreshCw size={17} className={busy?'animate-spin':''}/>{busy?(isLocal?'正在分析…':'正在刷新…'):(isLocal?'立即分析':'刷新数据')}</button></div></header>
<div className="mx-auto max-w-7xl space-y-5 px-4 py-5 sm:px-6">{error&&<div className="rounded-xl border border-amber-500/30 bg-amber-500/10 px-4 py-3 text-sm text-amber-200">{error}。定时数据仍可正常展示；电脑手动分析需启动本地桥接。</div>}
<section className="grid gap-5 lg:grid-cols-[1.5fr_.8fr]"><article className="rounded-3xl border border-[#d7a73c]/25 bg-gradient-to-br from-[#191814] to-[#101214] p-5 shadow-2xl shadow-black/20 sm:p-7"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs font-medium text-zinc-500">当前抓取价格</p><div className="mt-1 text-4xl font-semibold tracking-tight text-[#f3c75f] sm:text-5xl">{c?c.price.toFixed(2):'—'}</div><p className="mt-3 text-xs text-zinc-500">{c?`生成于 ${new Date(c.created_at).toLocaleString('zh-CN')}`:'等待首次数据'}</p><h1 className="mt-5 text-2xl font-semibold sm:text-3xl">{c?(c.decision==='trade'?`值得等待${labels[c.direction]}条件`:'当前空仓'):'尚未生成预测'}</h1><p className="mt-3 text-sm leading-7 text-zinc-400">{c?`有效至 ${new Date(c.valid_until).toLocaleString('zh-CN')}，模型 ${c.model_version}`:'请保持 MT5 在线后运行本地工作流。'}</p></div><span className={'h-fit rounded-full px-3 py-1.5 text-sm '+(c?.decision==='trade'?'bg-emerald-400/10 text-emerald-300':'bg-amber-400/10 text-amber-300')}>{c?.decision==='trade'?'有条件交易':'不交易'}</span></div>
<div className="mt-7 grid gap-3 sm:grid-cols-3">{probs.map(x=><div key={x[0] as string} className={'metric '+(c?.direction===x[2]?'selected':'')}><span>{x[0]}</span><strong>{fp(x[1] as number)}</strong></div>)}</div>
<div className="mt-5 grid gap-3 md:grid-cols-2"><div className="rule"><b className="text-emerald-300">执行条件</b>{parse(c?.execution_json).map((x:string)=><p key={x}>• {x}</p>)}</div><div className="rule"><b className="text-rose-300">放弃条件</b>{parse(c?.abandon_json).map((x:string)=><p key={x}>• {x}</p>)}</div></div><div className="mt-3 rounded-xl bg-black/25 p-4 text-sm">目标价格区间：<b className="text-[#e3b64f]">{c?`${c.target_low}–${c.target_high}`:'—'}</b></div></article>
<aside className="rounded-3xl border border-white/8 bg-[#111417] p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">系统状态</h2><ShieldCheck className="text-emerald-400" size={20}/></div>{['MT5 M5/M15/M30/H1','MACD · Stoch · ADX · MA','新闻与经济日历','只读模式，禁止自动下单'].map(x=><div key={x} className="mt-3 rounded-xl bg-white/[.035] px-3 py-3 text-sm text-zinc-300">✓ {x}</div>)}<div className="mt-4 rounded-xl bg-black/25 p-4 text-sm"><div className="flex items-center gap-2"><CalendarClock size={16} className="text-[#ddb657]"/>固定运行</div><p className="mt-2 leading-6 text-zinc-500">10:00 · 16:00 · 21:00<br/>每次先结算上一预测。</p></div></aside></section>
<section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['已结算样本',s?.samples??0,'20个样本后生成校准报告'],['方向命中率',fp(s?.direction_hit_rate),'滚动20次'],['目标区间命中',fp(s?.target_range_hit_rate),'到期价格落入区间'],['Brier分数',s?.brier?.toFixed(3)??'—','越低越好']].map(x=><div key={x[0] as string} className="rounded-2xl border border-white/8 bg-[#111417] p-5"><span className="text-sm text-zinc-500">{x[0]}</span><div className="mt-2 text-2xl font-semibold">{x[1]}</div><p className="mt-1 text-xs text-zinc-500">{x[2]}</p></div>)}</section>
<footer className="py-3 text-center text-xs text-zinc-600">研究与决策辅助 · 不承诺盈利 · 不执行交易</footer></div></main>}


